### ISSUE TITLE
Freewordsの削除フラグが追加できない。

### ISSUE THREAD

**Issue by sice11** [sice11/sns_app#3]
以下Freewordsに関する実行手順と最後のエラー内容

```
rails g controller Freewords new edit
```

```
rails g model Freeword word:string
```

```
rails db:migrate
```

```
rails g migration add_del_flg_to_freewords
```

sns_app\db\migrate\20200915155814_add_del_flg_to_freewords.rb 以下の内容を

```
class AddDelFlgToFreewords < ActiveRecord::Migration[5.1]
  def change
    add_column :freewords, del_flg, :integer, default:0
  end
end

```

と記述後、

```
rails db:migrate
```

実施

以下エラー内容

```
== 20200915155814 AddDelFlgToFreewords: migrating =============================
-- del_flg()
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined local variable or method `del_flg' for #<AddDelFlgToFreewords:0x0613e228>
C:/work/Rails/sns_app/db/migrate/20200915155814_add_del_flg_to_freewords.rb:3:in `change'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
NameError: undefined local variable or method `del_flg' for #<AddDelFlgToFreewords:0x0613e228>
C:/work/Rails/sns_app/db/migrate/20200915155814_add_del_flg_to_freewords.rb:3:in `change'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by sice11** [comment]
sns_app\db\migrate\20200915155814_add_del_flg_to_freewords.rb

ここでのdel_flg記述にミスあり

```
:del_flg
```

と記述する必要があった。

つまり、

: が抜けていた。
